### ISSUE TITLE
Virtual Machine Hangs when multiple instances of browser are run

### ISSUE THREAD

**Issue by arjunvenkatraman** [anandabhairav/xetrapal#1]
जब हम एक ही‌ वी‌एम पर एक से ज़्यादा ब्राउज़र लांच कर देते हैं तो वी‌एम हैंग होने लगता है। यही प्राबलम एक से अधिक Karta चलाने पर भी हो रही है

**Comment by anandabhairav** [comment]
Try increasing the number of processors on the VM.

**Comment by arjunvenkatraman** [comment]
Yup, sorts things out largely!
