### ISSUE TITLE
geckodriver issue needs to be resolved 

### ISSUE THREAD

**Issue by suryaveer5320129** [anandabhairav/xetrapal#3]
geckodriver is sometimes missing from the system of the user so kindly illustrate the use of geckodriver and the necessity of the geckodriver along with the configuration 
i have resolved the issue by the following commands
 $ geckodriver 
 $ which geckodriver
 $ cp /opt/SoMA/tools/geckodriver-v0.19.1-linux64.tar.gz .
 $ tar xvzf geckodriver-v0.19.1-linux64.tar.gz 
 $ ./geckodriver 
$ cp ./geckodriver /usr/bin/

**Comment by anandabhairav** [comment]
Generally it is best to get the latest binary for your distro. However, will package v0.19.1 anyway
